fix #2208: spark-submission failed due to lack of permission by user 'spark'
error: Exception in thread "main" java.io.FileNotFoundException: /home/spark/.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-511288aa-ce7c-4a38-9c8e-4869b71c68fa-1.0.xml (No such file or directory)
Signed-off-by: xuqingtan <missedone@gmail.com>