fix: spark-submission failed due to lack of permission by user `spark` (#2223)
error: Exception in thread "main" java.io.FileNotFoundException: /home/spark/.ivy2/cache/resolved-org.apache.spark-spark-submit-parent-511288aa-ce7c-4a38-9c8e-4869b71c68fa-1.0.xml (No such file or directory)

Signed-off-by: xuqingtan <missedone@gmail.com>
(cherry picked from commit d07821bcba84e60269244ccab898daa41176f493)
Signed-off-by: Yi Chen <github@chenyicn.net>